name: PR Gate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pr-gate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - "3.10"
          # - "3.11"
          # - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run linters
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
